// ============================================================
// allocation.study.test.ts — BLIND STUDY of the squad allocator.
// 100 synthetic kids (varied age / rep level / senior level / skill), generated by a
// seeded RNG with NO knowledge of the squads, run through the REAL DNA engine and then
// the allocator. We then verify the design invariants hold across the whole cohort:
//   SAFETY      no under-17 in a 17+ squad; nobody more than one band from their age.
//   CHALLENGE   top squads hold tier 4–5 only; Squad 1 holds tier 2–3 only (clean split).
//   BALANCE     every filled squad stays inside the 50/50 ±15% bat/bowl tolerance.
//   CAPACITY    no squad over its size.
//   FLOOR       below-2nd-grade / no-history players go to review, never a paid squad.
// ============================================================
import { describe, it, expect } from "vitest";
import { BLANK_FORM, computePlacement } from "../../components/power-game/apply/flow";
import { REP_GROUPS, CLUB_GROUPS, groupsForGender } from "../../components/power-game/apply/levels";
import {
  emptyState, assign, composition, bandIndex, SQUADS, QUOTA,
  type Player, type SkillKind, type BowlKind, type Band,
} from "./allocation";

// ---- deterministic RNG (mulberry32) so the study is reproducible ----
function mulberry32(seed: number) {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(20260610);
const pick = <T,>(arr: T[]): T => arr[Math.floor(rand() * arr.length)];
const chance = (p: number) => rand() < p;

const CENTRES = ["hallam", "williamstown", "mickleham"];
const FORM_SKILLS = ["batting", "batting", "bowling", "bowling", "all_rounder", "wicketkeeper"]; // ~rough mix
const skillMap: Record<string, SkillKind> = { batting: "bat", bowling: "bowl", all_rounder: "allrounder", wicketkeeper: "keeper" };
const repCodes = (g: string) => groupsForGender(REP_GROUPS, g).flatMap((gr) => gr.options.map((o) => o.code));
const clubCodes = (g: string) => groupsForGender(CLUB_GROUPS, g).flatMap((gr) => gr.options.map((o) => o.code));

interface StudyPlayer extends Player { age: number; engineTier: number; offers: number; }

function buildCohort(): StudyPlayer[] {
  const out: StudyPlayer[] = [];
  for (let i = 0; i < 100; i++) {
    const gender = chance(0.5) ? "M" : "F";
    const age = 11 + Math.floor(rand() * 10); // 11..20
    const dob = `${2026 - age}-0${1 + Math.floor(rand() * 8)}-15`;
    const skill = pick(FORM_SKILLS);
    const reps = repCodes(gender);
    const clubs = clubCodes(gender);
    const bowls = skill === "bowling" || skill === "all_rounder";
    const bowling_type = pick(["pace", "pace", "leg_spin", "off_spin"]);
    const form = {
      ...BLANK_FORM,
      gender, player_dob: dob, skill, batting_hand: "right",
      bowling_type: bowls ? bowling_type : "",
      rep_level: chance(0.45) && reps.length ? pick(reps) : "",
      club_level: chance(0.55) && clubs.length ? pick(clubs) : "",
      format: pick(["t20", "od", "multiday"]),
      rep_bat_avg: String(20 + Math.floor(rand() * 30)),
      club_bat_avg: String(20 + Math.floor(rand() * 30)),
      rep_bowl_avg: String(15 + Math.floor(rand() * 20)),
      club_bowl_avg: String(15 + Math.floor(rand() * 20)),
      rep_bowl_wkts: String(Math.floor(rand() * 25)),
      club_bowl_wkts: String(Math.floor(rand() * 25)),
    } as typeof BLANK_FORM;

    const { dna, placement } = computePlacement(form);
    const review = placement.requiresReview || !placement.placedBand;
    out.push({
      id: `p${i}`,
      band: (placement.placedBand || "12-14") as Band,
      tier: review ? "review" : placement.stream === "performance" ? "top" : "squad1",
      skill: skillMap[skill],
      bowl: bowls ? ((bowling_type === "pace" ? "pace" : "spin") as BowlKind) : null,
      score: dna.abilityTier ?? 0,
      centre: pick(CENTRES),
      age,
      engineTier: dna.abilityTier ?? 0,
      offers: 0,
    });
  }
  return out;
}

const chrono = (age: number): Band => (age <= 13 ? "12-14" : age <= 16 ? "14-16" : "17+");

// ---- run the study once ----
const cohort = buildCohort();
const states = emptyState();
const placed: { p: StudyPlayer; band: Band; tier: string; centre: string; session: string }[] = [];
const review: StudyPlayer[] = [];
const waitlist: StudyPlayer[] = [];
for (const p of cohort) {
  const res = assign(p, states);
  if (res.status === "placed") {
    p.offers = res.offers.length;
    placed.push({ p, band: res.squad.def.band, tier: res.squad.def.tier, centre: res.squad.def.centreName, session: res.squad.def.session });
  } else if (res.status === "review") review.push(p);
  else waitlist.push(p);
}

// ---- print the report ----
function report() {
  const lines: string[] = [];
  lines.push(`\n========== BLIND STUDY: 100 players ==========`);
  lines.push(`placed: ${placed.length} · review: ${review.length} · waitlist (no fit/full): ${waitlist.length}`);
  const by = (arr: { band: Band; tier: string }[], k: "band" | "tier") =>
    arr.reduce((m: Record<string, number>, x) => ((m[x[k]] = (m[x[k]] || 0) + 1), m), {});
  lines.push(`placed by band: ${JSON.stringify(by(placed, "band"))}`);
  lines.push(`placed by tier: ${JSON.stringify(by(placed, "tier"))}`);
  const avgOffers = placed.reduce((s, x) => s + x.p.offers, 0) / (placed.length || 1);
  lines.push(`avg session options offered (placed): ${avgOffers.toFixed(2)}`);
  lines.push(`\n--- squads (fill · bat% · spinners · keepers) ---`);
  for (const s of states) {
    if (!s.members.length) continue;
    const c = composition(s.members);
    const batPct = c.total ? Math.round((c.batSide / c.total) * 100) : 0;
    lines.push(
      `${s.def.centreName} ${s.def.session} ${s.def.band} ${s.def.tier}: ` +
      `${s.members.length}/${s.def.capacity} · bat ${batPct}% · spin ${c.spin} · kpr ${c.keeper}`,
    );
  }
  return lines.join("\n");
}

describe("Blind study — squad allocator over 100 random kids", () => {
  it("prints the allocation report", () => {
    console.log(report());
    expect(placed.length).toBeGreaterThan(0);
  });

  it("CAPACITY — no squad is over its size", () => {
    for (const s of states) expect(s.members.length).toBeLessThanOrEqual(s.def.capacity);
  });

  it("SAFETY — only 16+ performance minors reach 17+; nobody more than one band from age", () => {
    for (const { p, band } of placed) {
      if (band === "17+") {
        expect(p.age, `${p.id} age ${p.age} in 17+`).toBeGreaterThanOrEqual(16); // 16 allowed if performance
        if (p.age === 16) expect(p.engineTier, `${p.id} 16yo in 17+ must be performance`).toBeGreaterThanOrEqual(4);
      }
      const dist = Math.abs(bandIndex(band) - bandIndex(chrono(p.age)));
      expect(dist, `${p.id} age ${p.age} → ${band}`).toBeLessThanOrEqual(1);
    }
  });

  it("CHALLENGE — top squads hold tier 4–5 only; Squad 1 holds tier 2–3 only", () => {
    for (const { p, tier } of placed) {
      if (tier === "top") expect(p.engineTier, `${p.id}`).toBeGreaterThanOrEqual(4);
      else expect(p.engineTier, `${p.id}`).toBeLessThanOrEqual(3);
    }
  });

  it("BALANCE — every filled squad stays inside 50/50 ±tolerance", () => {
    for (const s of states) {
      const c = composition(s.members);
      if (c.total < QUOTA.balanceFloorSize) continue;
      const batPct = c.batSide / c.total;
      expect(batPct, `${s.def.id} bat% ${(batPct * 100).toFixed(0)}`).toBeGreaterThanOrEqual(QUOTA.batTarget - QUOTA.tolerance - 1e-9);
      expect(batPct, `${s.def.id} bat% ${(batPct * 100).toFixed(0)}`).toBeLessThanOrEqual(QUOTA.batTarget + QUOTA.tolerance + 1e-9);
    }
  });

  it("FLOOR — review players are never placed in a squad", () => {
    const placedIds = new Set(placed.map((x) => x.p.id));
    for (const r of review) expect(placedIds.has(r.id)).toBe(false);
    expect(review.every((r) => r.tier === "review")).toBe(true);
  });
});

describe("16yo at performance level may train with adults (17+)", () => {
  const at16 = (rep: string, club: string) => {
    const form = {
      ...BLANK_FORM, gender: "M", player_dob: "2010-01-15", skill: "batting", batting_hand: "right",
      rep_level: rep, club_level: club, format: "t20", rep_bat_avg: "42", club_bat_avg: "42",
    } as typeof BLANK_FORM;
    return computePlacement(form).placement;
  };
  // Dowling is U16 cricket — a 16yo playing it is age-appropriate (NOT playing up), so the
  // engine keeps them in the 14-16 top squad, not with adults. (A 15yo at Dowling is gun-for-age.)
  it("Dowling Shield at 16 (U16, age-appropriate) → 14-16 top, not adults", () => { const p = at16("P16M", ""); expect(p.placedBand, JSON.stringify(p)).toBe("14-16"); expect(p.requiresReview).toBe(false); });
  it("Vic U17 Emerging / EPP (rep) → 17+, no review", () => { const p = at16("VP-17M", ""); expect(p.placedBand, JSON.stringify(p)).toBe("17+"); expect(p.requiresReview).toBe(false); });
  it("Premier 3rd XI (senior) → 17+, no review", () => { const p = at16("", "P3M"); expect(p.placedBand, JSON.stringify(p)).toBe("17+"); expect(p.requiresReview).toBe(false); });
});
